### PR TITLE
adds information about HUSH season 4 activation

### PR DESCRIPTION
**Pull request by gcharang**

### CODE REVIEW

**Comment by phm87** [comment]
@gcharang do you know what about Game? They didn't merge the PR so I don't think that they warned exchanges https://github.com/gamecredits-project/GameCredits/pull/34

Edit: I see about 4 exchanges here including Bittrex: https://www.coingecko.com/en/coins/gamecredits#markets

**Comment by gcharang** [comment]
> do you know what about Game?

I don't have any concrete details, but heard that they have moved on to an ERC20 token. The person involved in adding dPoW to GAME said so https://discord.com/channels/412898016371015680/455851625915875338/720467148245303320

**Comment by phm87** [comment]
if we are sure that GameCredits running on Bittrex is an ERC-xx, it is fine. I though that it was GIN that moved to erc-xx and Game was still on its chain and moving to erc was a plan for future.
I will read a little bit.

Thank you for your time

edit: it is defined as an erc 20 on their website https://gamecredits.org/ so it is fine.

**Comment by phm87** [comment]
As discussed on discord, Greer showed us that Game will move to ERC 20 on July 1st.
https://medium.com/@gamecredits/game-credits-update-may-2020-16a740f7d489

We should continue to notarize it with S3 3P keys during 16 days, Hush won't be alone. ^^

**Comment by samadsajanlal** [comment]
Hi gents, are s3 keys still active? GAME is having transactions that are not confirmed by dpow.

**Comment by ca333** [comment]
> Hi gents, are s3 keys still active? GAME is having transactions that are not confirmed by dpow.

Hi, we updated to S4 on June 14th. https://github.com/gamecredits-project/GameCredits/pull/34

**Comment by samadsajanlal** [comment]
> > Hi gents, are s3 keys still active? GAME is having transactions that are not confirmed by dpow.
> 
> Hi, we updated to S4 on June 14th. [gamecredits-project/GameCredits#34](https://github.com/gamecredits-project/GameCredits/pull/34)

I understand that. But the situation is we are only having the current blockchain for another 2.5 weeks. We are trying to avoid releasing a new client so close to the swap. We're asking here (and in discord #support) if its possible to have a time extension on DPOW and notarizations w/ s3 keys during this time.

**Comment by ca333** [comment]
> > > Hi gents, are s3 keys still active? GAME is having transactions that are not confirmed by dpow.
> > 
> > 
> > Hi, we updated to S4 on June 14th. [gamecredits-project/GameCredits#34](https://github.com/gamecredits-project/GameCredits/pull/34)
> 
> I understand that. But the situation is we are only having the current blockchain for another 2.5 weeks. We are trying to avoid releasing a new client so close to the swap. We're asking here (and in discord #support) if its possible to have a time extension on DPOW and notarizations w/ s3 keys during this time.

yes, our QA lead @tonymorony is arranging this. Will keep you posted when we have enough S3 ops willing to run dPoW for game.

**Comment by samadsajanlal** [comment]
Thank you. From a planning perspective, if there are not enough S3 ops willing to support dPoW on game -- is it sufficient to have all exchanges and at least a few miners update to S4?

**Comment by tonymorony** [comment]
> Thank you. From a planning perspective, if there are not enough S3 ops willing to support dPoW on game -- is it sufficient to have all exchanges and at least a few miners update to S4?

Discussed situation and that particular question in Discord with n64. For transparency: Notarization pubkeys change is a forking change and all full nodes should update in case of changing that, otherwise chain will split on forks.

**Pull request merged**
